name: Publish Postman collection

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Postman collection that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Release Postman collection
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          fern generate --group postman --version ${{ inputs.version }} --log-level debug
